In [1]:
import torch

In [ ]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)
x.grad

In [ ]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
x.grad == 4*x

tensor([True, True, True, True])

In [ ]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [2]:
x1 = torch.tensor(2.0, requires_grad=True)
x2 = torch.tensor(0.0, requires_grad=True)

w1 = torch.tensor(-3.0, requires_grad=True)
w2 = torch.tensor(1.0, requires_grad=True)

b = torch.tensor(6.8813735870195432, requires_grad=True)

n = x1*w1 + x2*w2 + b
o = torch.tanh(n)
o.backward()

In [3]:
print(x1.grad)
print(x2.grad)
print(w1.grad)
print(w2.grad)

tensor(-1.5000)
tensor(0.5000)
tensor(1.0000)
tensor(0.)
